#!/usr/bin/env bash
# Generate and load the launchd job for THIS checkout.
#
# deploy/com.alpaca.optionsagent.plist cannot be installed directly: launchd
# needs absolute paths, so the committed copy carries whichever machine wrote it
# (it currently points at /Users/nizarhazaymeh/Desktop/bot). Copying it to
# ~/Library/LaunchAgents on any other machine produces a job that loads fine and
# silently never runs — the same class of failure the watchdog exists to prevent.
#
# This derives the paths from where it is actually checked out.
#
#   ./scripts/install_watchdog.sh            # install for ACCOUNT=comp
#   ACCOUNT=dev ./scripts/install_watchdog.sh
#   ./scripts/install_watchdog.sh --uninstall
set -euo pipefail
cd "$(dirname "$0")/.."
ROOT="$PWD"
ACCOUNT="${ACCOUNT:-comp}"
INTERVAL="${INTERVAL:-300}"
LABEL="com.alpaca.optionsagent"
DEST="$HOME/Library/LaunchAgents/$LABEL.plist"

if [ "${1:-}" = "--uninstall" ]; then
  launchctl unload -w "$DEST" 2>/dev/null || true
  rm -f "$DEST"
  echo "uninstalled $LABEL"
  exit 0
fi

mkdir -p "$HOME/Library/LaunchAgents" "$ROOT/logs"
cat > "$DEST" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- generated by scripts/install_watchdog.sh for $ROOT — do not hand-edit -->
<plist version="1.0">
<dict>
  <key>Label</key><string>$LABEL</string>
  <key>ProgramArguments</key>
  <array>
    <string>/bin/bash</string>
    <string>$ROOT/scripts/supervise.sh</string>
  </array>
  <key>WorkingDirectory</key><string>$ROOT</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>ACCOUNT</key><string>$ACCOUNT</string>
    <key>INTERVAL</key><string>$INTERVAL</string>
  </dict>
  <key>RunAtLoad</key><true/>
  <!-- KeepAlive, not StartInterval. A periodic nondemand spawn is advisory and
       launchd deferred it indefinitely on 3 Sep (runs=1 after 29 minutes).
       supervise.sh sleeps internally, so the cadence is ours, and KeepAlive
       only has to do the one thing it is reliable at: restart a dead process. -->
  <key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>$ROOT/logs/watchdog.log</string>
  <key>StandardErrorPath</key><string>$ROOT/logs/watchdog.log</string>
</dict>
</plist>
PLIST

plutil -lint "$DEST"
launchctl unload -w "$DEST" 2>/dev/null || true
launchctl load -w "$DEST"
sleep 6
if launchctl list | grep -q "$LABEL"; then
  echo "loaded $LABEL for ACCOUNT=$ACCOUNT every ${INTERVAL}s"
  echo "  root: $ROOT"
  n=$(pgrep -f "run.py loop" | wc -l | tr -d ' ')
  echo "  loops running: $n"
  [ "$n" -gt 1 ] && echo "  ⚠️  more than one loop — check ACCOUNT on each" || true
else
  echo "FAILED to load $LABEL"; exit 1
fi
